image: maven:3.6.1

definitions:
  steps:
    - step: &release
        name: release
        trigger: manual
        services:
          - docker
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh

          - mvn --batch-mode deploy -DskipTests=true -Dversion=1.${BITBUCKET_BUILD_NUMBER}.0
    - step: &run-tests
        name: run-tests
        caches:
          - maven
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          # Install the config files to the home directory and add env vars
          - source .artifactory/activate.sh
          # The script puts a settings.xml in the home directory so you can use mvn immediately
          - bash bin/configure-pipelines.sh
          - mvn -B verify -Dversion=1.${BITBUCKET_BUILD_NUMBER} # -B batch mode makes Maven less verbose

pipelines:
  default:
    - step: *run-tests

  branches:
    master:
      - step: *run-tests
      - step: *release
